FROM ruby:3.1.6-alpine

ENV BUILD_PACKAGES="curl-dev build-base openssh"

ENV DEV_PACKAGES="tzdata libxml2-dev libxslt-dev postgresql-dev imagemagick imagemagick-dev git gmp-dev nodejs npm"

RUN apk --update --upgrade add $BUILD_PACKAGES $DEV_PACKAGES && rm -rf /var/cache/apk/*
RUN npm install -g yarn

ENV RAILS_ROOT=/var/www/BioModelos
RUN mkdir -p $RAILS_ROOT
WORKDIR $RAILS_ROOT

COPY . .

ENTRYPOINT ["sh", "/var/www/BioModelos/entrypoint.dev.sh"]

