services:
  biomodelos_prod:
    image: biomodelos:prod
    build:
      context: .
      args:
        - RAILS_ENV=${RAILS_ENV}
    container_name: Biomodelos_website
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - RAILS_MASTER_KEY=${PRODUCTION_MASTER_KEY}
    volumes:
     - /path/to/host/methods:/var/www/BioModelos/public/methods
     - /path/to/host/models:/var/www/BioModelos/public/models
     - /path/to/host/thumbs:/var/www/BioModelos/public/thumbs
     - /path/to/host/zip:/var/www/BioModelos/public/zip
     - /path/to/host/uploads:/var/www/BioModelos/public/uploads
    ports:
     - "3000:3000"
    command: bundle exec rails server -b 0.0.0.0

  biomodelos_dev:
    image: biomodelos:dev
    build:
      context: .
      args:
        - RAILS_ENV=${RAILS_ENV}
    container_name: Biomodelos_website_dev
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - RAILS_MASTER_KEY=${DEVELOPMENT_MASTER_KEY}
    volumes:
     - /path/to/host/methods:/var/www/BioModelos/public/methods
     - /path/to/host/models:/var/www/BioModelos/public/models
     - /path/to/host/thumbs:/var/www/BioModelos/public/thumbs
     - /path/to/host/zip:/var/www/BioModelos/public/zip
     - /path/to/host/uploads:/var/www/BioModelos/public/uploads
    ports:
     - "3001:3000"
    command: bundle exec rails server -b 0.0.0.0
