openapi: 3.1.0
info:
  title: BioModelos API
  description: |
    Welcome to the BioModelos API! This API has been designed to provide easy and fast access to valuable information about the biodiversity of Colombia. We offer users a series of endpoints to access different services related to BioModelos, and we will be updating and expanding it as we develop new services and functionalities.

    The availability of this API is based on our conviction that access to information and collaboration are fundamental for biodiversity research and conservation. By offering this Application Programming Interface (API), we aim to facilitate access to data and services related to BioModelos, encouraging the active participation of the scientific community and users interested in Colombia's biodiversity.

    The first step to use our API is to request an api-key. To obtain it, please write to biomodelos@humboldt.org.co where steps to get it would be explained. Once you have your api-key, you can use all the services that our API offers. Remember to review the documentation for each endpoint, quickly accessible through the left-hand menu.
  version: 2.0.0
servers:
  - url: /v2
paths:
  /species/search/{searchWord}:
    parameters:
      - name: searchWord
        in: path
        required: true
        schema:
          type: string
          description: Full or partial name of the species to query
          example: abari
    get:
      tags: ["species"]
      operationId: searchSpecies
      summary: Species ID
      description: This endpoint allows you to search for the ID of a specific species. With this service, users can easily and efficiently access the unique ID assigned to each species in our database.
      responses:
        "200":
          description: Successfull operation
          content:
            application/json:
              schema:
                type: array
                description: Species array
                items:
                  $ref: "#/components/schemas/species"
                example:
                  $ref: "#/components/examples/speciesArray"

  /species/records/{taxID}:
    parameters:
    - name: taxID
      in: path
      required: true
      schema:
        type: integer
        description: Species id to query records
        example: 7010
    get:
      tags: ["species"]
      operationId: speciesRecords
      summary: Download records
      description: This endpoint provides access to public and curated records of a species, providing reliable and quality data on the presence of said species, a fundamental first step for the generation of new distribution models.
      responses:
        "200":
          description: Successfull operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    description: object type
                    example: FeatureCollection
                  features:
                    type: array
                    description: Points array with properties of every record
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          description: object type
                          example: Feature
                        geometry:
                          type: object
                          description: Features geometry information
                          properties:
                            type:
                              type: string
                              description: object type
                              example: Point
                            coordinates:
                              type: array
                              description: Values to desribe point coordenates
                              items:
                                type: number
                                format: double
                              example: [-75.910772, 9.183333]
                        properties:
                          $ref: '#/components/schemas/recordProps'

  /models:
    post:
      tags: ["models"]
      operationId: uploadModel
      summary: Load model
      description: This endpoint is intended to load models generated by experts. This allows researchers and scientists to share and collaborate in the development of distribution models, which promotes collaboration and knowledge exchange within the BioModelos community, benefiting the conservation and study of biodiversity.
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                taxID:
                  type: integer
                  description: Id of the species to which the model corresponds
                  example: 1234
                biomodelos_user:
                  type: string
                  description: username on BioModelos platform
                  example: my_username
                cc_license:
                  type: string
                  enum:
                    - by
                    - by-sa
                    - by-nc
                    - by-nc-sa
                    - cc-zero
                  description: License type according to the creative commons licenses (https://creativecommons.org/licenses/)
                  example: cc-zero
                atlas_agreement:
                  type: boolean
                  description: "Accept or deny the publishing of the model in the Atlas of Biodiversity of Colombia (más información: http://biomodelos.humboldt.org.co/publicacion.pdf)"
                  example: true
                model:
                  type: string
                  format: binary
                  description: Zip file with model data.

      responses:
        "204":
          description: Model received successfully
        "400":
          description: Some fields in the request are missing or the loaded file has a wrong format.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "'model' field is required and has to be a .zip file"

security:
  - api_key: []

tags:
  - name: species
    description: Operations related with available species in BioModelos
  - name: models
    description: Operations related to the models that are available or desired to be available in BioModelos

components:
  schemas:
    recordProps:
      type: object
      properties:
        _id:
          type: string
          description: Record id
          example: 5824a337e21cc54c32cbcb1d
        species:
          type: string
          description: Species name
          example: Alouatta palliata
        acceptedNameUsage:
          type: string
          description: Species accepted name
          example: Alouatta palliata
        source:
          type: string
          description: Name of the resource if is an online database or dataset name. The original name of the file (or a short name related).
          example: primatesARA
        speciesOriginal:
          type: string
          description: Original scientific name of the record.
          example: Alouatta palliata
        catalogNumber:
          type: string
          description: An identifier for the record within the data set or collection.
          example: null
        basisOfRecord:
          type: string
          description: The specific nature of the data record
          default: null
          enum:
          - PRESERVED_SPECIMEN
          - FOSSIL_SPECIMEN
          - LIVING_SPECIMEN
          - HUMAN_OBSERVATION
          - MACHINE_OBSERVATION
          - STILL_IMAGE
          - MOVING_IMAGE
          - SOUND_RECORDING
          - MATERIAL_SAMPLE
          - OCCURRENCE
          - OTHER_SPECIMEN
          example: HUMAN_OBSERVATION
        suggestedStateProvince:
          type: string
          description: Suggested state/province based on the record coordinates.
          example: Córdoba
        suggestedCounty:
          type: string
          description: Suggested county based on the record coordinates.
          example: LORICA
        taxID:
          type: integer
          description: Id associated with the species
          example: 7010
        url:
          type: string
          description: URL of the record
          example: null
        environmentalOutlier:
          type: boolean
          description: The record is marked as an environmental outlier by BioGeo package (R-package).
          example: false
        collectionCode:
          type: string
          description: The name, acronym, coden, or initialism identifying the collection or data set from which the record was derived.
          example: null
        county:
          type: string
          description: The name of the next smaller administrative region than state province
          example: Lorica
        day:
          type: integer
          description: The integer day of the month on which the Event occurred.
          example: null
        institutionCode:
          type: string
          description: The name in use by the institution having custody of the object(s) or information referred to in the record.
          example: null
        month:
          type: integer
          description: The ordinal month in which the Event occurred.
          example: null
        recordedBy:
          type: string
          description: The collector of the specimen/record.
          example: Díaz-J C
        stateProvince:
          type: string
          description: The name of the next smaller administrative region than country
          example: Córdoba
        verbatimElevation:
          type: string
          description:  The original description of the elevation (altitude, usually above sea level) of the Location.
          example: "0-0"
        verbatimLocality:
          type: string
          description: The original textual description of the place.
          example: Ceiba Pareja
        year:
          type: integer
          description: The four-digit year in which the Event occurred, according to the Common Era Calendar.
          example: null
        reported:
          type: boolean
          description: If the record has been reported
          example: false
        updated:
          description: false si the record hasn't been modified, or an array with version history.
          oneOf:
            - type: boolean
              example: false
            - type: array
              items:
                $ref: '#/components/schemas/recordProps'

    species:
      type: object
      description: Information about an speceis
      properties:
        species:
          type: string
          description: Species name
        taxID:
          type: integer
          description: Species ID

  examples:
    speciesArray:
      value:
        - species: Elleanthus cinnabarinus
          taxID: 7506
        - species: Hoplias malabaricus
          taxID: 5858

  securitySchemes:
    api_key:
      type: apiKey
      name: Authorization
      in: header
