module RecordsHelper
  def basisOfRecords
    return [
      'PreservedSpecimen',
      'FossilSpecimen',
      'LivingSpecimen',
      'HumanObservation',
      'MachineObservation',
      'MaterialSample',
      'Occurrence',
      'MaterialCitation',
  ].sort!
  end

  def states
    return [
      'ANTIOQUIA',
      'ATLÁNTICO',
      'BOGOTÁ, D.C.',
      'BOLÍVAR',
      'BOYACÁ',
      'CALDAS',
      'CAQUETÁ',
      'CAUCA',
      'CESAR',
      'CÓRDOBA',
      'CUNDINAMARCA',
      'CHOCÓ',
      'HUILA',
      'LA GUAJIRA',
      'MAGDALENA',
      'META',
      'NARIÑO',
      'NORTE DE SANTANDER',
      'QUINDÍO',
      'RISARALDA',
      'SANTANDER',
      'SUCRE',
      'TOLIMA',
      'VALLE DEL CAUCA',
      'ARAUCA',
      'CASANARE',
      'PUTUMAYO',
      'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA',
      'AMAZONAS',
      'GUAINÍA',
      'GUAVIARE',
      'VAUPÉS',
      'VICHADA'
    ].sort!
  end

  def counties
    return [
      ['ANTIOQUIA', 'MEDELLÍN'],
      ['ANTIOQUIA', 'ABEJORRAL'],
      ['ANTIOQUIA', 'ABRIAQUÍ'],
      ['ANTIOQUIA', 'ALEJANDRÍA'],
      ['ANTIOQUIA', 'AMAGÁ'],
      ['ANTIOQUIA', 'AMALFI'],
      ['ANTIOQUIA', 'ANDES'],
      ['ANTIOQUIA', 'ANGELÓPOLIS'],
      ['ANTIOQUIA', 'ANGOSTURA'],
      ['ANTIOQUIA', 'ANORÍ'],
      ['ANTIOQUIA', 'SANTA FÉ DE ANTIOQUIA'],
      ['ANTIOQUIA', 'ANZÁ'],
      ['ANTIOQUIA', 'APARTADÓ'],
      ['ANTIOQUIA', 'ARBOLETES'],
      ['ANTIOQUIA', 'ARGELIA'],
      ['ANTIOQUIA', 'ARMENIA'],
      ['ANTIOQUIA', 'BARBOSA'],
      ['ANTIOQUIA', 'BELMIRA'],
      ['ANTIOQUIA', 'BELLO'],
      ['ANTIOQUIA', 'BETANIA'],
      ['ANTIOQUIA', 'BETULIA'],
      ['ANTIOQUIA', 'CIUDAD BOLÍVAR'],
      ['ANTIOQUIA', 'BRICEÑO'],
      ['ANTIOQUIA', 'BURITICÁ'],
      ['ANTIOQUIA', 'CÁCERES'],
      ['ANTIOQUIA', 'CAICEDO'],
      ['ANTIOQUIA', 'CALDAS'],
      ['ANTIOQUIA', 'CAMPAMENTO'],
      ['ANTIOQUIA', 'CAÑASGORDAS'],
      ['ANTIOQUIA', 'CARACOLÍ'],
      ['ANTIOQUIA', 'CARAMANTA'],
      ['ANTIOQUIA', 'CAREPA'],
      ['ANTIOQUIA', 'EL CARMEN DE VIBORAL'],
      ['ANTIOQUIA', 'CAROLINA'],
      ['ANTIOQUIA', 'CAUCASIA'],
      ['ANTIOQUIA', 'CHIGORODÓ'],
      ['ANTIOQUIA', 'CISNEROS'],
      ['ANTIOQUIA', 'COCORNÁ'],
      ['ANTIOQUIA', 'CONCEPCIÓN'],
      ['ANTIOQUIA', 'CONCORDIA'],
      ['ANTIOQUIA', 'COPACABANA'],
      ['ANTIOQUIA', 'DABEIBA'],
      ['ANTIOQUIA', 'DONMATÍAS'],
      ['ANTIOQUIA', 'EBÉJICO'],
      ['ANTIOQUIA', 'EL BAGRE'],
      ['ANTIOQUIA', 'ENTRERRÍOS'],
      ['ANTIOQUIA', 'ENVIGADO'],
      ['ANTIOQUIA', 'FREDONIA'],
      ['ANTIOQUIA', 'FRONTINO'],
      ['ANTIOQUIA', 'GIRALDO'],
      ['ANTIOQUIA', 'GIRARDOTA'],
      ['ANTIOQUIA', 'GÓMEZ PLATA'],
      ['ANTIOQUIA', 'GRANADA'],
      ['ANTIOQUIA', 'GUADALUPE'],
      ['ANTIOQUIA', 'GUARNE'],
      ['ANTIOQUIA', 'GUATAPÉ'],
      ['ANTIOQUIA', 'HELICONIA'],
      ['ANTIOQUIA', 'HISPANIA'],
      ['ANTIOQUIA', 'ITAGÜÍ'],
      ['ANTIOQUIA', 'ITUANGO'],
      ['ANTIOQUIA', 'JARDÍN'],
      ['ANTIOQUIA', 'JERICÓ'],
      ['ANTIOQUIA', 'LA CEJA'],
      ['ANTIOQUIA', 'LA ESTRELLA'],
      ['ANTIOQUIA', 'LA PINTADA'],
      ['ANTIOQUIA', 'LA UNIÓN'],
      ['ANTIOQUIA', 'LIBORINA'],
      ['ANTIOQUIA', 'MACEO'],
      ['ANTIOQUIA', 'MARINILLA'],
      ['ANTIOQUIA', 'MONTEBELLO'],
      ['ANTIOQUIA', 'MURINDÓ'],
      ['ANTIOQUIA', 'MUTATÁ'],
      ['ANTIOQUIA', 'NARIÑO'],
      ['ANTIOQUIA', 'NECOCLÍ'],
      ['ANTIOQUIA', 'NECHÍ'],
      ['ANTIOQUIA', 'OLAYA'],
      ['ANTIOQUIA', 'PEÑOL'],
      ['ANTIOQUIA', 'PEQUE'],
      ['ANTIOQUIA', 'PUEBLORRICO'],
      ['ANTIOQUIA', 'PUERTO BERRÍO'],
      ['ANTIOQUIA', 'PUERTO NARE'],
      ['ANTIOQUIA', 'PUERTO TRIUNFO'],
      ['ANTIOQUIA', 'REMEDIOS'],
      ['ANTIOQUIA', 'RETIRO'],
      ['ANTIOQUIA', 'RIONEGRO'],
      ['ANTIOQUIA', 'SABANALARGA'],
      ['ANTIOQUIA', 'SABANETA'],
      ['ANTIOQUIA', 'SALGAR'],
      ['ANTIOQUIA', 'SAN ANDRÉS DE CUERQUÍA'],
      ['ANTIOQUIA', 'SAN CARLOS'],
      ['ANTIOQUIA', 'SAN FRANCISCO'],
      ['ANTIOQUIA', 'SAN JERÓNIMO'],
      ['ANTIOQUIA', 'SAN JOSÉ DE LA MONTAÑA'],
      ['ANTIOQUIA', 'SAN JUAN DE URABÁ'],
      ['ANTIOQUIA', 'SAN LUIS'],
      ['ANTIOQUIA', 'SAN PEDRO DE LOS MILAGROS'],
      ['ANTIOQUIA', 'SAN PEDRO DE URABÁ'],
      ['ANTIOQUIA', 'SAN RAFAEL'],
      ['ANTIOQUIA', 'SAN ROQUE'],
      ['ANTIOQUIA', 'SAN VICENTE FERRER'],
      ['ANTIOQUIA', 'SANTA BÁRBARA'],
      ['ANTIOQUIA', 'SANTA ROSA DE OSOS'],
      ['ANTIOQUIA', 'SANTO DOMINGO'],
      ['ANTIOQUIA', 'EL SANTUARIO'],
      ['ANTIOQUIA', 'SEGOVIA'],
      ['ANTIOQUIA', 'SONSÓN'],
      ['ANTIOQUIA', 'SOPETRÁN'],
      ['ANTIOQUIA', 'TÁMESIS'],
      ['ANTIOQUIA', 'TARAZÁ'],
      ['ANTIOQUIA', 'TARSO'],
      ['ANTIOQUIA', 'TITIRIBÍ'],
      ['ANTIOQUIA', 'TOLEDO'],
      ['ANTIOQUIA', 'TURBO'],
      ['ANTIOQUIA', 'URAMITA'],
      ['ANTIOQUIA', 'URRAO'],
      ['ANTIOQUIA', 'VALDIVIA'],
      ['ANTIOQUIA', 'VALPARAÍSO'],
      ['ANTIOQUIA', 'VEGACHÍ'],
      ['ANTIOQUIA', 'VENECIA'],
      ['ANTIOQUIA', 'VIGÍA DEL FUERTE'],
      ['ANTIOQUIA', 'YALÍ'],
      ['ANTIOQUIA', 'YARUMAL'],
      ['ANTIOQUIA', 'YOLOMBÓ'],
      ['ANTIOQUIA', 'YONDÓ'],
      ['ANTIOQUIA', 'ZARAGOZA'],
      ['ATLÁNTICO', 'BARRANQUILLA'],
      ['ATLÁNTICO', 'BARANOA'],
      ['ATLÁNTICO', 'CAMPO DE LA CRUZ'],
      ['ATLÁNTICO', 'CANDELARIA'],
      ['ATLÁNTICO', 'GALAPA'],
      ['ATLÁNTICO', 'JUAN DE ACOSTA'],
      ['ATLÁNTICO', 'LURUACO'],
      ['ATLÁNTICO', 'MALAMBO'],
      ['ATLÁNTICO', 'MANATÍ'],
      ['ATLÁNTICO', 'PALMAR DE VARELA'],
      ['ATLÁNTICO', 'PIOJÓ'],
      ['ATLÁNTICO', 'POLONUEVO'],
      ['ATLÁNTICO', 'PONEDERA'],
      ['ATLÁNTICO', 'PUERTO COLOMBIA'],
      ['ATLÁNTICO', 'REPELÓN'],
      ['ATLÁNTICO', 'SABANAGRANDE'],
      ['ATLÁNTICO', 'SABANALARGA'],
      ['ATLÁNTICO', 'SANTA LUCÍA'],
      ['ATLÁNTICO', 'SANTO TOMÁS'],
      ['ATLÁNTICO', 'SOLEDAD'],
      ['ATLÁNTICO', 'SUAN'],
      ['ATLÁNTICO', 'TUBARÁ'],
      ['ATLÁNTICO', 'USIACURÍ'],
      ['BOGOTÁ, D.C.', 'BOGOTÁ, D.C.'],
      ['BOLÍVAR', 'CARTAGENA DE INDIAS'],
      ['BOLÍVAR', 'ACHÍ'],
      ['BOLÍVAR', 'ALTOS DEL ROSARIO'],
      ['BOLÍVAR', 'ARENAL'],
      ['BOLÍVAR', 'ARJONA'],
      ['BOLÍVAR', 'ARROYOHONDO'],
      ['BOLÍVAR', 'BARRANCO DE LOBA'],
      ['BOLÍVAR', 'CALAMAR'],
      ['BOLÍVAR', 'CANTAGALLO'],
      ['BOLÍVAR', 'CICUCO'],
      ['BOLÍVAR', 'CÓRDOBA'],
      ['BOLÍVAR', 'CLEMENCIA'],
      ['BOLÍVAR', 'EL CARMEN DE BOLÍVAR'],
      ['BOLÍVAR', 'EL GUAMO'],
      ['BOLÍVAR', 'EL PEÑÓN'],
      ['BOLÍVAR', 'HATILLO DE LOBA'],
      ['BOLÍVAR', 'MAGANGUÉ'],
      ['BOLÍVAR', 'MAHATES'],
      ['BOLÍVAR', 'MARGARITA'],
      ['BOLÍVAR', 'MARÍA LA BAJA'],
      ['BOLÍVAR', 'MONTECRISTO'],
      ['BOLÍVAR', 'SANTA CRUZ DE MOMPOX'],
      ['BOLÍVAR', 'MORALES'],
      ['BOLÍVAR', 'NOROSÍ'],
      ['BOLÍVAR', 'PINILLOS'],
      ['BOLÍVAR', 'REGIDOR'],
      ['BOLÍVAR', 'RÍO VIEJO'],
      ['BOLÍVAR', 'SAN CRISTÓBAL'],
      ['BOLÍVAR', 'SAN ESTANISLAO'],
      ['BOLÍVAR', 'SAN FERNANDO'],
      ['BOLÍVAR', 'SAN JACINTO'],
      ['BOLÍVAR', 'SAN JACINTO DEL CAUCA'],
      ['BOLÍVAR', 'SAN JUAN NEPOMUCENO'],
      ['BOLÍVAR', 'SAN MARTÍN DE LOBA'],
      ['BOLÍVAR', 'SAN PABLO'],
      ['BOLÍVAR', 'SANTA CATALINA'],
      ['BOLÍVAR', 'SANTA ROSA'],
      ['BOLÍVAR', 'SANTA ROSA DEL SUR'],
      ['BOLÍVAR', 'SIMITÍ'],
      ['BOLÍVAR', 'SOPLAVIENTO'],
      ['BOLÍVAR', 'TALAIGUA NUEVO'],
      ['BOLÍVAR', 'TIQUISIO'],
      ['BOLÍVAR', 'TURBACO'],
      ['BOLÍVAR', 'TURBANÁ'],
      ['BOLÍVAR', 'VILLANUEVA'],
      ['BOLÍVAR', 'ZAMBRANO'],
      ['BOYACÁ', 'TUNJA'],
      ['BOYACÁ', 'ALMEIDA'],
      ['BOYACÁ', 'AQUITANIA'],
      ['BOYACÁ', 'ARCABUCO'],
      ['BOYACÁ', 'BELÉN'],
      ['BOYACÁ', 'BERBEO'],
      ['BOYACÁ', 'BETÉITIVA'],
      ['BOYACÁ', 'BOAVITA'],
      ['BOYACÁ', 'BOYACÁ'],
      ['BOYACÁ', 'BRICEÑO'],
      ['BOYACÁ', 'BUENAVISTA'],
      ['BOYACÁ', 'BUSBANZÁ'],
      ['BOYACÁ', 'CALDAS'],
      ['BOYACÁ', 'CAMPOHERMOSO'],
      ['BOYACÁ', 'CERINZA'],
      ['BOYACÁ', 'CHINAVITA'],
      ['BOYACÁ', 'CHIQUINQUIRÁ'],
      ['BOYACÁ', 'CHISCAS'],
      ['BOYACÁ', 'CHITA'],
      ['BOYACÁ', 'CHITARAQUE'],
      ['BOYACÁ', 'CHIVATÁ'],
      ['BOYACÁ', 'CIÉNEGA'],
      ['BOYACÁ', 'CÓMBITA'],
      ['BOYACÁ', 'COPER'],
      ['BOYACÁ', 'CORRALES'],
      ['BOYACÁ', 'COVARACHÍA'],
      ['BOYACÁ', 'CUBARÁ'],
      ['BOYACÁ', 'CUCAITA'],
      ['BOYACÁ', 'CUÍTIVA'],
      ['BOYACÁ', 'CHÍQUIZA'],
      ['BOYACÁ', 'CHIVOR'],
      ['BOYACÁ', 'DUITAMA'],
      ['BOYACÁ', 'EL COCUY'],
      ['BOYACÁ', 'EL ESPINO'],
      ['BOYACÁ', 'FIRAVITOBA'],
      ['BOYACÁ', 'FLORESTA'],
      ['BOYACÁ', 'GACHANTIVÁ'],
      ['BOYACÁ', 'GÁMEZA'],
      ['BOYACÁ', 'GARAGOA'],
      ['BOYACÁ', 'GUACAMAYAS'],
      ['BOYACÁ', 'GUATEQUE'],
      ['BOYACÁ', 'GUAYATÁ'],
      ['BOYACÁ', 'GÜICÁN DE LA SIERRA'],
      ['BOYACÁ', 'IZA'],
      ['BOYACÁ', 'JENESANO'],
      ['BOYACÁ', 'JERICÓ'],
      ['BOYACÁ', 'LABRANZAGRANDE'],
      ['BOYACÁ', 'LA CAPILLA'],
      ['BOYACÁ', 'LA VICTORIA'],
      ['BOYACÁ', 'LA UVITA'],
      ['BOYACÁ', 'VILLA DE LEYVA'],
      ['BOYACÁ', 'MACANAL'],
      ['BOYACÁ', 'MARIPÍ'],
      ['BOYACÁ', 'MIRAFLORES'],
      ['BOYACÁ', 'MONGUA'],
      ['BOYACÁ', 'MONGUÍ'],
      ['BOYACÁ', 'MONIQUIRÁ'],
      ['BOYACÁ', 'MOTAVITA'],
      ['BOYACÁ', 'MUZO'],
      ['BOYACÁ', 'NOBSA'],
      ['BOYACÁ', 'NUEVO COLÓN'],
      ['BOYACÁ', 'OICATÁ'],
      ['BOYACÁ', 'OTANCHE'],
      ['BOYACÁ', 'PACHAVITA'],
      ['BOYACÁ', 'PÁEZ'],
      ['BOYACÁ', 'PAIPA'],
      ['BOYACÁ', 'PAJARITO'],
      ['BOYACÁ', 'PANQUEBA'],
      ['BOYACÁ', 'PAUNA'],
      ['BOYACÁ', 'PAYA'],
      ['BOYACÁ', 'PAZ DE RÍO'],
      ['BOYACÁ', 'PESCA'],
      ['BOYACÁ', 'PISBA'],
      ['BOYACÁ', 'PUERTO BOYACÁ'],
      ['BOYACÁ', 'QUÍPAMA'],
      ['BOYACÁ', 'RAMIRIQUÍ'],
      ['BOYACÁ', 'RÁQUIRA'],
      ['BOYACÁ', 'RONDÓN'],
      ['BOYACÁ', 'SABOYÁ'],
      ['BOYACÁ', 'SÁCHICA'],
      ['BOYACÁ', 'SAMACÁ'],
      ['BOYACÁ', 'SAN EDUARDO'],
      ['BOYACÁ', 'SAN JOSÉ DE PARE'],
      ['BOYACÁ', 'SAN LUIS DE GACENO'],
      ['BOYACÁ', 'SAN MATEO'],
      ['BOYACÁ', 'SAN MIGUEL DE SEMA'],
      ['BOYACÁ', 'SAN PABLO DE BORBUR'],
      ['BOYACÁ', 'SANTANA'],
      ['BOYACÁ', 'SANTA MARÍA'],
      ['BOYACÁ', 'SANTA ROSA DE VITERBO'],
      ['BOYACÁ', 'SANTA SOFÍA'],
      ['BOYACÁ', 'SATIVANORTE'],
      ['BOYACÁ', 'SATIVASUR'],
      ['BOYACÁ', 'SIACHOQUE'],
      ['BOYACÁ', 'SOATÁ'],
      ['BOYACÁ', 'SOCOTÁ'],
      ['BOYACÁ', 'SOCHA'],
      ['BOYACÁ', 'SOGAMOSO'],
      ['BOYACÁ', 'SOMONDOCO'],
      ['BOYACÁ', 'SORA'],
      ['BOYACÁ', 'SOTAQUIRÁ'],
      ['BOYACÁ', 'SORACÁ'],
      ['BOYACÁ', 'SUSACÓN'],
      ['BOYACÁ', 'SUTAMARCHÁN'],
      ['BOYACÁ', 'SUTATENZA'],
      ['BOYACÁ', 'TASCO'],
      ['BOYACÁ', 'TENZA'],
      ['BOYACÁ', 'TIBANÁ'],
      ['BOYACÁ', 'TIBASOSA'],
      ['BOYACÁ', 'TINJACÁ'],
      ['BOYACÁ', 'TIPACOQUE'],
      ['BOYACÁ', 'TOCA'],
      ['BOYACÁ', 'TOGÜÍ'],
      ['BOYACÁ', 'TÓPAGA'],
      ['BOYACÁ', 'TOTA'],
      ['BOYACÁ', 'TUNUNGUÁ'],
      ['BOYACÁ', 'TURMEQUÉ'],
      ['BOYACÁ', 'TUTA'],
      ['BOYACÁ', 'TUTAZÁ'],
      ['BOYACÁ', 'ÚMBITA'],
      ['BOYACÁ', 'VENTAQUEMADA'],
      ['BOYACÁ', 'VIRACACHÁ'],
      ['BOYACÁ', 'ZETAQUIRA'],
      ['CALDAS', 'MANIZALES'],
      ['CALDAS', 'AGUADAS'],
      ['CALDAS', 'ANSERMA'],
      ['CALDAS', 'ARANZAZU'],
      ['CALDAS', 'BELALCÁZAR'],
      ['CALDAS', 'CHINCHINÁ'],
      ['CALDAS', 'FILADELFIA'],
      ['CALDAS', 'LA DORADA'],
      ['CALDAS', 'LA MERCED'],
      ['CALDAS', 'MANZANARES'],
      ['CALDAS', 'MARMATO'],
      ['CALDAS', 'MARQUETALIA'],
      ['CALDAS', 'MARULANDA'],
      ['CALDAS', 'NEIRA'],
      ['CALDAS', 'NORCASIA'],
      ['CALDAS', 'PÁCORA'],
      ['CALDAS', 'PALESTINA'],
      ['CALDAS', 'PENSILVANIA'],
      ['CALDAS', 'RIOSUCIO'],
      ['CALDAS', 'RISARALDA'],
      ['CALDAS', 'SALAMINA'],
      ['CALDAS', 'SAMANÁ'],
      ['CALDAS', 'SAN JOSÉ'],
      ['CALDAS', 'SUPÍA'],
      ['CALDAS', 'VICTORIA'],
      ['CALDAS', 'VILLAMARÍA'],
      ['CALDAS', 'VITERBO'],
      ['CAQUETÁ', 'FLORENCIA'],
      ['CAQUETÁ', 'ALBANIA'],
      ['CAQUETÁ', 'BELÉN DE LOS ANDAQUÍES'],
      ['CAQUETÁ', 'CARTAGENA DEL CHAIRÁ'],
      ['CAQUETÁ', 'CURILLO'],
      ['CAQUETÁ', 'EL DONCELLO'],
      ['CAQUETÁ', 'EL PAUJÍL'],
      ['CAQUETÁ', 'LA MONTAÑITA'],
      ['CAQUETÁ', 'MILÁN'],
      ['CAQUETÁ', 'MORELIA'],
      ['CAQUETÁ', 'PUERTO RICO'],
      ['CAQUETÁ', 'SAN JOSÉ DEL FRAGUA'],
      ['CAQUETÁ', 'SAN VICENTE DEL CAGUÁN'],
      ['CAQUETÁ', 'SOLANO'],
      ['CAQUETÁ', 'SOLITA'],
      ['CAQUETÁ', 'VALPARAÍSO'],
      ['CAUCA', 'POPAYÁN'],
      ['CAUCA', 'ALMAGUER'],
      ['CAUCA', 'ARGELIA'],
      ['CAUCA', 'BALBOA'],
      ['CAUCA', 'BOLÍVAR'],
      ['CAUCA', 'BUENOS AIRES'],
      ['CAUCA', 'CAJIBÍO'],
      ['CAUCA', 'CALDONO'],
      ['CAUCA', 'CALOTO'],
      ['CAUCA', 'CORINTO'],
      ['CAUCA', 'EL TAMBO'],
      ['CAUCA', 'FLORENCIA'],
      ['CAUCA', 'GUACHENÉ'],
      ['CAUCA', 'GUAPI'],
      ['CAUCA', 'INZÁ'],
      ['CAUCA', 'JAMBALÓ'],
      ['CAUCA', 'LA SIERRA'],
      ['CAUCA', 'LA VEGA'],
      ['CAUCA', 'LÓPEZ DE MICAY'],
      ['CAUCA', 'MERCADERES'],
      ['CAUCA', 'MIRANDA'],
      ['CAUCA', 'MORALES'],
      ['CAUCA', 'PADILLA'],
      ['CAUCA', 'PÁEZ'],
      ['CAUCA', 'PATÍA'],
      ['CAUCA', 'PIAMONTE'],
      ['CAUCA', 'PIENDAMÓ - TUNÍA'],
      ['CAUCA', 'PUERTO TEJADA'],
      ['CAUCA', 'PURACÉ'],
      ['CAUCA', 'ROSAS'],
      ['CAUCA', 'SAN SEBASTIÁN'],
      ['CAUCA', 'SANTANDER DE QUILICHAO'],
      ['CAUCA', 'SANTA ROSA'],
      ['CAUCA', 'SILVIA'],
      ['CAUCA', 'SOTARÁ PAISPAMBA'],
      ['CAUCA', 'SUÁREZ'],
      ['CAUCA', 'SUCRE'],
      ['CAUCA', 'TIMBÍO'],
      ['CAUCA', 'TIMBIQUÍ'],
      ['CAUCA', 'TORIBÍO'],
      ['CAUCA', 'TOTORÓ'],
      ['CAUCA', 'VILLA RICA'],
      ['CESAR', 'VALLEDUPAR'],
      ['CESAR', 'AGUACHICA'],
      ['CESAR', 'AGUSTÍN CODAZZI'],
      ['CESAR', 'ASTREA'],
      ['CESAR', 'BECERRIL'],
      ['CESAR', 'BOSCONIA'],
      ['CESAR', 'CHIMICHAGUA'],
      ['CESAR', 'CHIRIGUANÁ'],
      ['CESAR', 'CURUMANÍ'],
      ['CESAR', 'EL COPEY'],
      ['CESAR', 'EL PASO'],
      ['CESAR', 'GAMARRA'],
      ['CESAR', 'GONZÁLEZ'],
      ['CESAR', 'LA GLORIA'],
      ['CESAR', 'LA JAGUA DE IBIRICO'],
      ['CESAR', 'MANAURE BALCÓN DEL CESAR'],
      ['CESAR', 'PAILITAS'],
      ['CESAR', 'PELAYA'],
      ['CESAR', 'PUEBLO BELLO'],
      ['CESAR', 'RÍO DE ORO'],
      ['CESAR', 'LA PAZ'],
      ['CESAR', 'SAN ALBERTO'],
      ['CESAR', 'SAN DIEGO'],
      ['CESAR', 'SAN MARTÍN'],
      ['CESAR', 'TAMALAMEQUE'],
      ['CÓRDOBA', 'MONTERÍA'],
      ['CÓRDOBA', 'AYAPEL'],
      ['CÓRDOBA', 'BUENAVISTA'],
      ['CÓRDOBA', 'CANALETE'],
      ['CÓRDOBA', 'CERETÉ'],
      ['CÓRDOBA', 'CHIMÁ'],
      ['CÓRDOBA', 'CHINÚ'],
      ['CÓRDOBA', 'CIÉNAGA DE ORO'],
      ['CÓRDOBA', 'COTORRA'],
      ['CÓRDOBA', 'LA APARTADA'],
      ['CÓRDOBA', 'LORICA'],
      ['CÓRDOBA', 'LOS CÓRDOBAS'],
      ['CÓRDOBA', 'MOMIL'],
      ['CÓRDOBA', 'MONTELÍBANO'],
      ['CÓRDOBA', 'MOÑITOS'],
      ['CÓRDOBA', 'PLANETA RICA'],
      ['CÓRDOBA', 'PUEBLO NUEVO'],
      ['CÓRDOBA', 'PUERTO ESCONDIDO'],
      ['CÓRDOBA', 'PUERTO LIBERTADOR'],
      ['CÓRDOBA', 'PURÍSIMA DE LA CONCEPCIÓN'],
      ['CÓRDOBA', 'SAHAGÚN'],
      ['CÓRDOBA', 'SAN ANDRÉS DE SOTAVENTO'],
      ['CÓRDOBA', 'SAN ANTERO'],
      ['CÓRDOBA', 'SAN BERNARDO DEL VIENTO'],
      ['CÓRDOBA', 'SAN CARLOS'],
      ['CÓRDOBA', 'SAN JOSÉ DE URÉ'],
      ['CÓRDOBA', 'SAN PELAYO'],
      ['CÓRDOBA', 'TIERRALTA'],
      ['CÓRDOBA', 'TUCHÍN'],
      ['CÓRDOBA', 'VALENCIA'],
      ['CUNDINAMARCA', 'AGUA DE DIOS'],
      ['CUNDINAMARCA', 'ALBÁN'],
      ['CUNDINAMARCA', 'ANAPOIMA'],
      ['CUNDINAMARCA', 'ANOLAIMA'],
      ['CUNDINAMARCA', 'ARBELÁEZ'],
      ['CUNDINAMARCA', 'BELTRÁN'],
      ['CUNDINAMARCA', 'BITUIMA'],
      ['CUNDINAMARCA', 'BOJACÁ'],
      ['CUNDINAMARCA', 'CABRERA'],
      ['CUNDINAMARCA', 'CACHIPAY'],
      ['CUNDINAMARCA', 'CAJICÁ'],
      ['CUNDINAMARCA', 'CAPARRAPÍ'],
      ['CUNDINAMARCA', 'CÁQUEZA'],
      ['CUNDINAMARCA', 'CARMEN DE CARUPA'],
      ['CUNDINAMARCA', 'CHAGUANÍ'],
      ['CUNDINAMARCA', 'CHÍA'],
      ['CUNDINAMARCA', 'CHIPAQUE'],
      ['CUNDINAMARCA', 'CHOACHÍ'],
      ['CUNDINAMARCA', 'CHOCONTÁ'],
      ['CUNDINAMARCA', 'COGUA'],
      ['CUNDINAMARCA', 'COTA'],
      ['CUNDINAMARCA', 'CUCUNUBÁ'],
      ['CUNDINAMARCA', 'EL COLEGIO'],
      ['CUNDINAMARCA', 'EL PEÑÓN'],
      ['CUNDINAMARCA', 'EL ROSAL'],
      ['CUNDINAMARCA', 'FACATATIVÁ'],
      ['CUNDINAMARCA', 'FÓMEQUE'],
      ['CUNDINAMARCA', 'FOSCA'],
      ['CUNDINAMARCA', 'FUNZA'],
      ['CUNDINAMARCA', 'FÚQUENE'],
      ['CUNDINAMARCA', 'FUSAGASUGÁ'],
      ['CUNDINAMARCA', 'GACHALÁ'],
      ['CUNDINAMARCA', 'GACHANCIPÁ'],
      ['CUNDINAMARCA', 'GACHETÁ'],
      ['CUNDINAMARCA', 'GAMA'],
      ['CUNDINAMARCA', 'GIRARDOT'],
      ['CUNDINAMARCA', 'GRANADA'],
      ['CUNDINAMARCA', 'GUACHETÁ'],
      ['CUNDINAMARCA', 'GUADUAS'],
      ['CUNDINAMARCA', 'GUASCA'],
      ['CUNDINAMARCA', 'GUATAQUÍ'],
      ['CUNDINAMARCA', 'GUATAVITA'],
      ['CUNDINAMARCA', 'GUAYABAL DE SÍQUIMA'],
      ['CUNDINAMARCA', 'GUAYABETAL'],
      ['CUNDINAMARCA', 'GUTIÉRREZ'],
      ['CUNDINAMARCA', 'JERUSALÉN'],
      ['CUNDINAMARCA', 'JUNÍN'],
      ['CUNDINAMARCA', 'LA CALERA'],
      ['CUNDINAMARCA', 'LA MESA'],
      ['CUNDINAMARCA', 'LA PALMA'],
      ['CUNDINAMARCA', 'LA PEÑA'],
      ['CUNDINAMARCA', 'LA VEGA'],
      ['CUNDINAMARCA', 'LENGUAZAQUE'],
      ['CUNDINAMARCA', 'MACHETÁ'],
      ['CUNDINAMARCA', 'MADRID'],
      ['CUNDINAMARCA', 'MANTA'],
      ['CUNDINAMARCA', 'MEDINA'],
      ['CUNDINAMARCA', 'MOSQUERA'],
      ['CUNDINAMARCA', 'NARIÑO'],
      ['CUNDINAMARCA', 'NEMOCÓN'],
      ['CUNDINAMARCA', 'NILO'],
      ['CUNDINAMARCA', 'NIMAIMA'],
      ['CUNDINAMARCA', 'NOCAIMA'],
      ['CUNDINAMARCA', 'VENECIA'],
      ['CUNDINAMARCA', 'PACHO'],
      ['CUNDINAMARCA', 'PAIME'],
      ['CUNDINAMARCA', 'PANDI'],
      ['CUNDINAMARCA', 'PARATEBUENO'],
      ['CUNDINAMARCA', 'PASCA'],
      ['CUNDINAMARCA', 'PUERTO SALGAR'],
      ['CUNDINAMARCA', 'PULÍ'],
      ['CUNDINAMARCA', 'QUEBRADANEGRA'],
      ['CUNDINAMARCA', 'QUETAME'],
      ['CUNDINAMARCA', 'QUIPILE'],
      ['CUNDINAMARCA', 'APULO'],
      ['CUNDINAMARCA', 'RICAURTE'],
      ['CUNDINAMARCA', 'SAN ANTONIO DEL TEQUENDAMA'],
      ['CUNDINAMARCA', 'SAN BERNARDO'],
      ['CUNDINAMARCA', 'SAN CAYETANO'],
      ['CUNDINAMARCA', 'SAN FRANCISCO'],
      ['CUNDINAMARCA', 'SAN JUAN DE RIOSECO'],
      ['CUNDINAMARCA', 'SASAIMA'],
      ['CUNDINAMARCA', 'SESQUILÉ'],
      ['CUNDINAMARCA', 'SIBATÉ'],
      ['CUNDINAMARCA', 'SILVANIA'],
      ['CUNDINAMARCA', 'SIMIJACA'],
      ['CUNDINAMARCA', 'SOACHA'],
      ['CUNDINAMARCA', 'SOPÓ'],
      ['CUNDINAMARCA', 'SUBACHOQUE'],
      ['CUNDINAMARCA', 'SUESCA'],
      ['CUNDINAMARCA', 'SUPATÁ'],
      ['CUNDINAMARCA', 'SUSA'],
      ['CUNDINAMARCA', 'SUTATAUSA'],
      ['CUNDINAMARCA', 'TABIO'],
      ['CUNDINAMARCA', 'TAUSA'],
      ['CUNDINAMARCA', 'TENA'],
      ['CUNDINAMARCA', 'TENJO'],
      ['CUNDINAMARCA', 'TIBACUY'],
      ['CUNDINAMARCA', 'TIBIRITA'],
      ['CUNDINAMARCA', 'TOCAIMA'],
      ['CUNDINAMARCA', 'TOCANCIPÁ'],
      ['CUNDINAMARCA', 'TOPAIPÍ'],
      ['CUNDINAMARCA', 'UBALÁ'],
      ['CUNDINAMARCA', 'UBAQUE'],
      ['CUNDINAMARCA', 'VILLA DE SAN DIEGO DE UBATÉ'],
      ['CUNDINAMARCA', 'UNE'],
      ['CUNDINAMARCA', 'ÚTICA'],
      ['CUNDINAMARCA', 'VERGARA'],
      ['CUNDINAMARCA', 'VIANÍ'],
      ['CUNDINAMARCA', 'VILLAGÓMEZ'],
      ['CUNDINAMARCA', 'VILLAPINZÓN'],
      ['CUNDINAMARCA', 'VILLETA'],
      ['CUNDINAMARCA', 'VIOTÁ'],
      ['CUNDINAMARCA', 'YACOPÍ'],
      ['CUNDINAMARCA', 'ZIPACÓN'],
      ['CUNDINAMARCA', 'ZIPAQUIRÁ'],
      ['CHOCÓ', 'QUIBDÓ'],
      ['CHOCÓ', 'ACANDÍ'],
      ['CHOCÓ', 'ALTO BAUDÓ'],
      ['CHOCÓ', 'ATRATO'],
      ['CHOCÓ', 'BAGADÓ'],
      ['CHOCÓ', 'BAHÍA SOLANO'],
      ['CHOCÓ', 'BAJO BAUDÓ'],
      ['CHOCÓ', 'BOJAYÁ'],
      ['CHOCÓ', 'EL CANTÓN DEL SAN PABLO'],
      ['CHOCÓ', 'CARMEN DEL DARIÉN'],
      ['CHOCÓ', 'CÉRTEGUI'],
      ['CHOCÓ', 'CONDOTO'],
      ['CHOCÓ', 'EL CARMEN DE ATRATO'],
      ['CHOCÓ', 'EL LITORAL DEL SAN JUAN'],
      ['CHOCÓ', 'ISTMINA'],
      ['CHOCÓ', 'JURADÓ'],
      ['CHOCÓ', 'LLORÓ'],
      ['CHOCÓ', 'MEDIO ATRATO'],
      ['CHOCÓ', 'MEDIO BAUDÓ'],
      ['CHOCÓ', 'MEDIO SAN JUAN'],
      ['CHOCÓ', 'NÓVITA'],
      ['CHOCÓ', 'NUQUÍ'],
      ['CHOCÓ', 'RÍO IRÓ'],
      ['CHOCÓ', 'RÍO QUITO'],
      ['CHOCÓ', 'RIOSUCIO'],
      ['CHOCÓ', 'SAN JOSÉ DEL PALMAR'],
      ['CHOCÓ', 'SIPÍ'],
      ['CHOCÓ', 'TADÓ'],
      ['CHOCÓ', 'UNGUÍA'],
      ['CHOCÓ', 'UNIÓN PANAMERICANA'],
      ['HUILA', 'NEIVA'],
      ['HUILA', 'ACEVEDO'],
      ['HUILA', 'AGRADO'],
      ['HUILA', 'AIPE'],
      ['HUILA', 'ALGECIRAS'],
      ['HUILA', 'ALTAMIRA'],
      ['HUILA', 'BARAYA'],
      ['HUILA', 'CAMPOALEGRE'],
      ['HUILA', 'COLOMBIA'],
      ['HUILA', 'ELÍAS'],
      ['HUILA', 'GARZÓN'],
      ['HUILA', 'GIGANTE'],
      ['HUILA', 'GUADALUPE'],
      ['HUILA', 'HOBO'],
      ['HUILA', 'ÍQUIRA'],
      ['HUILA', 'ISNOS'],
      ['HUILA', 'LA ARGENTINA'],
      ['HUILA', 'LA PLATA'],
      ['HUILA', 'NÁTAGA'],
      ['HUILA', 'OPORAPA'],
      ['HUILA', 'PAICOL'],
      ['HUILA', 'PALERMO'],
      ['HUILA', 'PALESTINA'],
      ['HUILA', 'PITAL'],
      ['HUILA', 'PITALITO'],
      ['HUILA', 'RIVERA'],
      ['HUILA', 'SALADOBLANCO'],
      ['HUILA', 'SAN AGUSTÍN'],
      ['HUILA', 'SANTA MARÍA'],
      ['HUILA', 'SUAZA'],
      ['HUILA', 'TARQUI'],
      ['HUILA', 'TESALIA'],
      ['HUILA', 'TELLO'],
      ['HUILA', 'TERUEL'],
      ['HUILA', 'TIMANÁ'],
      ['HUILA', 'VILLAVIEJA'],
      ['HUILA', 'YAGUARÁ'],
      ['LA GUAJIRA', 'RIOHACHA'],
      ['LA GUAJIRA', 'ALBANIA'],
      ['LA GUAJIRA', 'BARRANCAS'],
      ['LA GUAJIRA', 'DIBULLA'],
      ['LA GUAJIRA', 'DISTRACCIÓN'],
      ['LA GUAJIRA', 'EL MOLINO'],
      ['LA GUAJIRA', 'FONSECA'],
      ['LA GUAJIRA', 'HATONUEVO'],
      ['LA GUAJIRA', 'LA JAGUA DEL PILAR'],
      ['LA GUAJIRA', 'MAICAO'],
      ['LA GUAJIRA', 'MANAURE'],
      ['LA GUAJIRA', 'SAN JUAN DEL CESAR'],
      ['LA GUAJIRA', 'URIBIA'],
      ['LA GUAJIRA', 'URUMITA'],
      ['LA GUAJIRA', 'VILLANUEVA'],
      ['MAGDALENA', 'SANTA MARTA'],
      ['MAGDALENA', 'ALGARROBO'],
      ['MAGDALENA', 'ARACATACA'],
      ['MAGDALENA', 'ARIGUANÍ'],
      ['MAGDALENA', 'CERRO DE SAN ANTONIO'],
      ['MAGDALENA', 'CHIVOLO'],
      ['MAGDALENA', 'CIÉNAGA'],
      ['MAGDALENA', 'CONCORDIA'],
      ['MAGDALENA', 'EL BANCO'],
      ['MAGDALENA', 'EL PIÑÓN'],
      ['MAGDALENA', 'EL RETÉN'],
      ['MAGDALENA', 'FUNDACIÓN'],
      ['MAGDALENA', 'GUAMAL'],
      ['MAGDALENA', 'NUEVA GRANADA'],
      ['MAGDALENA', 'PEDRAZA'],
      ['MAGDALENA', 'PIJIÑO DEL CARMEN'],
      ['MAGDALENA', 'PIVIJAY'],
      ['MAGDALENA', 'PLATO'],
      ['MAGDALENA', 'PUEBLOVIEJO'],
      ['MAGDALENA', 'REMOLINO'],
      ['MAGDALENA', 'SABANAS DE SAN ÁNGEL'],
      ['MAGDALENA', 'SALAMINA'],
      ['MAGDALENA', 'SAN SEBASTIÁN DE BUENAVISTA'],
      ['MAGDALENA', 'SAN ZENÓN'],
      ['MAGDALENA', 'SANTA ANA'],
      ['MAGDALENA', 'SANTA BÁRBARA DE PINTO'],
      ['MAGDALENA', 'SITIONUEVO'],
      ['MAGDALENA', 'TENERIFE'],
      ['MAGDALENA', 'ZAPAYÁN'],
      ['MAGDALENA', 'ZONA BANANERA'],
      ['META', 'VILLAVICENCIO'],
      ['META', 'ACACÍAS'],
      ['META', 'BARRANCA DE UPÍA'],
      ['META', 'CABUYARO'],
      ['META', 'CASTILLA LA NUEVA'],
      ['META', 'CUBARRAL'],
      ['META', 'CUMARAL'],
      ['META', 'EL CALVARIO'],
      ['META', 'EL CASTILLO'],
      ['META', 'EL DORADO'],
      ['META', 'FUENTE DE ORO'],
      ['META', 'GRANADA'],
      ['META', 'GUAMAL'],
      ['META', 'MAPIRIPÁN'],
      ['META', 'MESETAS'],
      ['META', 'LA MACARENA'],
      ['META', 'URIBE'],
      ['META', 'LEJANÍAS'],
      ['META', 'PUERTO CONCORDIA'],
      ['META', 'PUERTO GAITÁN'],
      ['META', 'PUERTO LÓPEZ'],
      ['META', 'PUERTO LLERAS'],
      ['META', 'PUERTO RICO'],
      ['META', 'RESTREPO'],
      ['META', 'SAN CARLOS DE GUAROA'],
      ['META', 'SAN JUAN DE ARAMA'],
      ['META', 'SAN JUANITO'],
      ['META', 'SAN MARTÍN'],
      ['META', 'VISTAHERMOSA'],
      ['NARIÑO', 'PASTO'],
      ['NARIÑO', 'ALBÁN'],
      ['NARIÑO', 'ALDANA'],
      ['NARIÑO', 'ANCUYA'],
      ['NARIÑO', 'ARBOLEDA'],
      ['NARIÑO', 'BARBACOAS'],
      ['NARIÑO', 'BELÉN'],
      ['NARIÑO', 'BUESACO'],
      ['NARIÑO', 'COLÓN'],
      ['NARIÑO', 'CONSACÁ'],
      ['NARIÑO', 'CONTADERO'],
      ['NARIÑO', 'CÓRDOBA'],
      ['NARIÑO', 'CUASPUD CARLOSAMA'],
      ['NARIÑO', 'CUMBAL'],
      ['NARIÑO', 'CUMBITARA'],
      ['NARIÑO', 'CHACHAGÜÍ'],
      ['NARIÑO', 'EL CHARCO'],
      ['NARIÑO', 'EL PEÑOL'],
      ['NARIÑO', 'EL ROSARIO'],
      ['NARIÑO', 'EL TABLÓN DE GÓMEZ'],
      ['NARIÑO', 'EL TAMBO'],
      ['NARIÑO', 'FUNES'],
      ['NARIÑO', 'GUACHUCAL'],
      ['NARIÑO', 'GUAITARILLA'],
      ['NARIÑO', 'GUALMATÁN'],
      ['NARIÑO', 'ILES'],
      ['NARIÑO', 'IMUÉS'],
      ['NARIÑO', 'IPIALES'],
      ['NARIÑO', 'LA CRUZ'],
      ['NARIÑO', 'LA FLORIDA'],
      ['NARIÑO', 'LA LLANADA'],
      ['NARIÑO', 'LA TOLA'],
      ['NARIÑO', 'LA UNIÓN'],
      ['NARIÑO', 'LEIVA'],
      ['NARIÑO', 'LINARES'],
      ['NARIÑO', 'LOS ANDES'],
      ['NARIÑO', 'MAGÜÍ'],
      ['NARIÑO', 'MALLAMA'],
      ['NARIÑO', 'MOSQUERA'],
      ['NARIÑO', 'NARIÑO'],
      ['NARIÑO', 'OLAYA HERRERA'],
      ['NARIÑO', 'OSPINA'],
      ['NARIÑO', 'FRANCISCO PIZARRO'],
      ['NARIÑO', 'POLICARPA'],
      ['NARIÑO', 'POTOSÍ'],
      ['NARIÑO', 'PROVIDENCIA'],
      ['NARIÑO', 'PUERRES'],
      ['NARIÑO', 'PUPIALES'],
      ['NARIÑO', 'RICAURTE'],
      ['NARIÑO', 'ROBERTO PAYÁN'],
      ['NARIÑO', 'SAMANIEGO'],
      ['NARIÑO', 'SANDONÁ'],
      ['NARIÑO', 'SAN BERNARDO'],
      ['NARIÑO', 'SAN LORENZO'],
      ['NARIÑO', 'SAN PABLO'],
      ['NARIÑO', 'SAN PEDRO DE CARTAGO'],
      ['NARIÑO', 'SANTA BÁRBARA'],
      ['NARIÑO', 'SANTACRUZ'],
      ['NARIÑO', 'SAPUYES'],
      ['NARIÑO', 'TAMINANGO'],
      ['NARIÑO', 'TANGUA'],
      ['NARIÑO', 'SAN ANDRÉS DE TUMACO'],
      ['NARIÑO', 'TÚQUERRES'],
      ['NARIÑO', 'YACUANQUER'],
      ['NORTE DE SANTANDER', 'SAN JOSÉ DE CÚCUTA'],
      ['NORTE DE SANTANDER', 'ÁBREGO'],
      ['NORTE DE SANTANDER', 'ARBOLEDAS'],
      ['NORTE DE SANTANDER', 'BOCHALEMA'],
      ['NORTE DE SANTANDER', 'BUCARASICA'],
      ['NORTE DE SANTANDER', 'CÁCOTA'],
      ['NORTE DE SANTANDER', 'CÁCHIRA'],
      ['NORTE DE SANTANDER', 'CHINÁCOTA'],
      ['NORTE DE SANTANDER', 'CHITAGÁ'],
      ['NORTE DE SANTANDER', 'CONVENCIÓN'],
      ['NORTE DE SANTANDER', 'CUCUTILLA'],
      ['NORTE DE SANTANDER', 'DURANIA'],
      ['NORTE DE SANTANDER', 'EL CARMEN'],
      ['NORTE DE SANTANDER', 'EL TARRA'],
      ['NORTE DE SANTANDER', 'EL ZULIA'],
      ['NORTE DE SANTANDER', 'GRAMALOTE'],
      ['NORTE DE SANTANDER', 'HACARÍ'],
      ['NORTE DE SANTANDER', 'HERRÁN'],
      ['NORTE DE SANTANDER', 'LABATECA'],
      ['NORTE DE SANTANDER', 'LA ESPERANZA'],
      ['NORTE DE SANTANDER', 'LA PLAYA'],
      ['NORTE DE SANTANDER', 'LOS PATIOS'],
      ['NORTE DE SANTANDER', 'LOURDES'],
      ['NORTE DE SANTANDER', 'MUTISCUA'],
      ['NORTE DE SANTANDER', 'OCAÑA'],
      ['NORTE DE SANTANDER', 'PAMPLONA'],
      ['NORTE DE SANTANDER', 'PAMPLONITA'],
      ['NORTE DE SANTANDER', 'PUERTO SANTANDER'],
      ['NORTE DE SANTANDER', 'RAGONVALIA'],
      ['NORTE DE SANTANDER', 'SALAZAR'],
      ['NORTE DE SANTANDER', 'SAN CALIXTO'],
      ['NORTE DE SANTANDER', 'SAN CAYETANO'],
      ['NORTE DE SANTANDER', 'SANTIAGO'],
      ['NORTE DE SANTANDER', 'SARDINATA'],
      ['NORTE DE SANTANDER', 'SILOS'],
      ['NORTE DE SANTANDER', 'TEORAMA'],
      ['NORTE DE SANTANDER', 'TIBÚ'],
      ['NORTE DE SANTANDER', 'TOLEDO'],
      ['NORTE DE SANTANDER', 'VILLA CARO'],
      ['NORTE DE SANTANDER', 'VILLA DEL ROSARIO'],
      ['QUINDÍO', 'ARMENIA'],
      ['QUINDÍO', 'BUENAVISTA'],
      ['QUINDÍO', 'CALARCÁ'],
      ['QUINDÍO', 'CIRCASIA'],
      ['QUINDÍO', 'CÓRDOBA'],
      ['QUINDÍO', 'FILANDIA'],
      ['QUINDÍO', 'GÉNOVA'],
      ['QUINDÍO', 'LA TEBAIDA'],
      ['QUINDÍO', 'MONTENEGRO'],
      ['QUINDÍO', 'PIJAO'],
      ['QUINDÍO', 'QUIMBAYA'],
      ['QUINDÍO', 'SALENTO'],
      ['RISARALDA', 'PEREIRA'],
      ['RISARALDA', 'APÍA'],
      ['RISARALDA', 'BALBOA'],
      ['RISARALDA', 'BELÉN DE UMBRÍA'],
      ['RISARALDA', 'DOSQUEBRADAS'],
      ['RISARALDA', 'GUÁTICA'],
      ['RISARALDA', 'LA CELIA'],
      ['RISARALDA', 'LA VIRGINIA'],
      ['RISARALDA', 'MARSELLA'],
      ['RISARALDA', 'MISTRATÓ'],
      ['RISARALDA', 'PUEBLO RICO'],
      ['RISARALDA', 'QUINCHÍA'],
      ['RISARALDA', 'SANTA ROSA DE CABAL'],
      ['RISARALDA', 'SANTUARIO'],
      ['SANTANDER', 'BUCARAMANGA'],
      ['SANTANDER', 'AGUADA'],
      ['SANTANDER', 'ALBANIA'],
      ['SANTANDER', 'ARATOCA'],
      ['SANTANDER', 'BARBOSA'],
      ['SANTANDER', 'BARICHARA'],
      ['SANTANDER', 'BARRANCABERMEJA'],
      ['SANTANDER', 'BETULIA'],
      ['SANTANDER', 'BOLÍVAR'],
      ['SANTANDER', 'CABRERA'],
      ['SANTANDER', 'CALIFORNIA'],
      ['SANTANDER', 'CAPITANEJO'],
      ['SANTANDER', 'CARCASÍ'],
      ['SANTANDER', 'CEPITÁ'],
      ['SANTANDER', 'CERRITO'],
      ['SANTANDER', 'CHARALÁ'],
      ['SANTANDER', 'CHARTA'],
      ['SANTANDER', 'CHIMA'],
      ['SANTANDER', 'CHIPATÁ'],
      ['SANTANDER', 'CIMITARRA'],
      ['SANTANDER', 'CONCEPCIÓN'],
      ['SANTANDER', 'CONFINES'],
      ['SANTANDER', 'CONTRATACIÓN'],
      ['SANTANDER', 'COROMORO'],
      ['SANTANDER', 'CURITÍ'],
      ['SANTANDER', 'EL CARMEN DE CHUCURÍ'],
      ['SANTANDER', 'EL GUACAMAYO'],
      ['SANTANDER', 'EL PEÑÓN'],
      ['SANTANDER', 'EL PLAYÓN'],
      ['SANTANDER', 'ENCINO'],
      ['SANTANDER', 'ENCISO'],
      ['SANTANDER', 'FLORIÁN'],
      ['SANTANDER', 'FLORIDABLANCA'],
      ['SANTANDER', 'GALÁN'],
      ['SANTANDER', 'GÁMBITA'],
      ['SANTANDER', 'GIRÓN'],
      ['SANTANDER', 'GUACA'],
      ['SANTANDER', 'GUADALUPE'],
      ['SANTANDER', 'GUAPOTÁ'],
      ['SANTANDER', 'GUAVATÁ'],
      ['SANTANDER', 'GÜEPSA'],
      ['SANTANDER', 'HATO'],
      ['SANTANDER', 'JESÚS MARÍA'],
      ['SANTANDER', 'JORDÁN'],
      ['SANTANDER', 'LA BELLEZA'],
      ['SANTANDER', 'LANDÁZURI'],
      ['SANTANDER', 'LA PAZ'],
      ['SANTANDER', 'LEBRIJA'],
      ['SANTANDER', 'LOS SANTOS'],
      ['SANTANDER', 'MACARAVITA'],
      ['SANTANDER', 'MÁLAGA'],
      ['SANTANDER', 'MATANZA'],
      ['SANTANDER', 'MOGOTES'],
      ['SANTANDER', 'MOLAGAVITA'],
      ['SANTANDER', 'OCAMONTE'],
      ['SANTANDER', 'OIBA'],
      ['SANTANDER', 'ONZAGA'],
      ['SANTANDER', 'PALMAR'],
      ['SANTANDER', 'PALMAS DEL SOCORRO'],
      ['SANTANDER', 'PÁRAMO'],
      ['SANTANDER', 'PIEDECUESTA'],
      ['SANTANDER', 'PINCHOTE'],
      ['SANTANDER', 'PUENTE NACIONAL'],
      ['SANTANDER', 'PUERTO PARRA'],
      ['SANTANDER', 'PUERTO WILCHES'],
      ['SANTANDER', 'RIONEGRO'],
      ['SANTANDER', 'SABANA DE TORRES'],
      ['SANTANDER', 'SAN ANDRÉS'],
      ['SANTANDER', 'SAN BENITO'],
      ['SANTANDER', 'SAN GIL'],
      ['SANTANDER', 'SAN JOAQUÍN'],
      ['SANTANDER', 'SAN JOSÉ DE MIRANDA'],
      ['SANTANDER', 'SAN MIGUEL'],
      ['SANTANDER', 'SAN VICENTE DE CHUCURÍ'],
      ['SANTANDER', 'SANTA BÁRBARA'],
      ['SANTANDER', 'SANTA HELENA DEL OPÓN'],
      ['SANTANDER', 'SIMACOTA'],
      ['SANTANDER', 'SOCORRO'],
      ['SANTANDER', 'SUAITA'],
      ['SANTANDER', 'SUCRE'],
      ['SANTANDER', 'SURATÁ'],
      ['SANTANDER', 'TONA'],
      ['SANTANDER', 'VALLE DE SAN JOSÉ'],
      ['SANTANDER', 'VÉLEZ'],
      ['SANTANDER', 'VETAS'],
      ['SANTANDER', 'VILLANUEVA'],
      ['SANTANDER', 'ZAPATOCA'],
      ['SUCRE', 'SINCELEJO'],
      ['SUCRE', 'BUENAVISTA'],
      ['SUCRE', 'CAIMITO'],
      ['SUCRE', 'COLOSÓ'],
      ['SUCRE', 'COROZAL'],
      ['SUCRE', 'COVEÑAS'],
      ['SUCRE', 'CHALÁN'],
      ['SUCRE', 'EL ROBLE'],
      ['SUCRE', 'GALERAS'],
      ['SUCRE', 'GUARANDA'],
      ['SUCRE', 'LA UNIÓN'],
      ['SUCRE', 'LOS PALMITOS'],
      ['SUCRE', 'MAJAGUAL'],
      ['SUCRE', 'MORROA'],
      ['SUCRE', 'OVEJAS'],
      ['SUCRE', 'PALMITO'],
      ['SUCRE', 'SAMPUÉS'],
      ['SUCRE', 'SAN BENITO ABAD'],
      ['SUCRE', 'SAN JUAN DE BETULIA'],
      ['SUCRE', 'SAN MARCOS'],
      ['SUCRE', 'SAN ONOFRE'],
      ['SUCRE', 'SAN PEDRO'],
      ['SUCRE', 'SAN LUIS DE SINCÉ'],
      ['SUCRE', 'SUCRE'],
      ['SUCRE', 'SANTIAGO DE TOLÚ'],
      ['SUCRE', 'SAN JOSÉ DE TOLUVIEJO'],
      ['TOLIMA', 'IBAGUÉ'],
      ['TOLIMA', 'ALPUJARRA'],
      ['TOLIMA', 'ALVARADO'],
      ['TOLIMA', 'AMBALEMA'],
      ['TOLIMA', 'ANZOÁTEGUI'],
      ['TOLIMA', 'ARMERO'],
      ['TOLIMA', 'ATACO'],
      ['TOLIMA', 'CAJAMARCA'],
      ['TOLIMA', 'CARMEN DE APICALÁ'],
      ['TOLIMA', 'CASABIANCA'],
      ['TOLIMA', 'CHAPARRAL'],
      ['TOLIMA', 'COELLO'],
      ['TOLIMA', 'COYAIMA'],
      ['TOLIMA', 'CUNDAY'],
      ['TOLIMA', 'DOLORES'],
      ['TOLIMA', 'ESPINAL'],
      ['TOLIMA', 'FALAN'],
      ['TOLIMA', 'FLANDES'],
      ['TOLIMA', 'FRESNO'],
      ['TOLIMA', 'GUAMO'],
      ['TOLIMA', 'HERVEO'],
      ['TOLIMA', 'HONDA'],
      ['TOLIMA', 'ICONONZO'],
      ['TOLIMA', 'LÉRIDA'],
      ['TOLIMA', 'LÍBANO'],
      ['TOLIMA', 'SAN SEBASTIÁN DE MARIQUITA'],
      ['TOLIMA', 'MELGAR'],
      ['TOLIMA', 'MURILLO'],
      ['TOLIMA', 'NATAGAIMA'],
      ['TOLIMA', 'ORTEGA'],
      ['TOLIMA', 'PALOCABILDO'],
      ['TOLIMA', 'PIEDRAS'],
      ['TOLIMA', 'PLANADAS'],
      ['TOLIMA', 'PRADO'],
      ['TOLIMA', 'PURIFICACIÓN'],
      ['TOLIMA', 'RIOBLANCO'],
      ['TOLIMA', 'RONCESVALLES'],
      ['TOLIMA', 'ROVIRA'],
      ['TOLIMA', 'SALDAÑA'],
      ['TOLIMA', 'SAN ANTONIO'],
      ['TOLIMA', 'SAN LUIS'],
      ['TOLIMA', 'SANTA ISABEL'],
      ['TOLIMA', 'SUÁREZ'],
      ['TOLIMA', 'VALLE DE SAN JUAN'],
      ['TOLIMA', 'VENADILLO'],
      ['TOLIMA', 'VILLAHERMOSA'],
      ['TOLIMA', 'VILLARRICA'],
      ['VALLE DEL CAUCA', 'CALI'],
      ['VALLE DEL CAUCA', 'ALCALÁ'],
      ['VALLE DEL CAUCA', 'ANDALUCÍA'],
      ['VALLE DEL CAUCA', 'ANSERMANUEVO'],
      ['VALLE DEL CAUCA', 'ARGELIA'],
      ['VALLE DEL CAUCA', 'BOLÍVAR'],
      ['VALLE DEL CAUCA', 'BUENAVENTURA'],
      ['VALLE DEL CAUCA', 'GUADALAJARA DE BUGA'],
      ['VALLE DEL CAUCA', 'BUGALAGRANDE'],
      ['VALLE DEL CAUCA', 'CAICEDONIA'],
      ['VALLE DEL CAUCA', 'CALIMA'],
      ['VALLE DEL CAUCA', 'CANDELARIA'],
      ['VALLE DEL CAUCA', 'CARTAGO'],
      ['VALLE DEL CAUCA', 'DAGUA'],
      ['VALLE DEL CAUCA', 'EL ÁGUILA'],
      ['VALLE DEL CAUCA', 'EL CAIRO'],
      ['VALLE DEL CAUCA', 'EL CERRITO'],
      ['VALLE DEL CAUCA', 'EL DOVIO'],
      ['VALLE DEL CAUCA', 'FLORIDA'],
      ['VALLE DEL CAUCA', 'GINEBRA'],
      ['VALLE DEL CAUCA', 'GUACARÍ'],
      ['VALLE DEL CAUCA', 'JAMUNDÍ'],
      ['VALLE DEL CAUCA', 'LA CUMBRE'],
      ['VALLE DEL CAUCA', 'LA UNIÓN'],
      ['VALLE DEL CAUCA', 'LA VICTORIA'],
      ['VALLE DEL CAUCA', 'OBANDO'],
      ['VALLE DEL CAUCA', 'PALMIRA'],
      ['VALLE DEL CAUCA', 'PRADERA'],
      ['VALLE DEL CAUCA', 'RESTREPO'],
      ['VALLE DEL CAUCA', 'RIOFRÍO'],
      ['VALLE DEL CAUCA', 'ROLDANILLO'],
      ['VALLE DEL CAUCA', 'SAN PEDRO'],
      ['VALLE DEL CAUCA', 'SEVILLA'],
      ['VALLE DEL CAUCA', 'TORO'],
      ['VALLE DEL CAUCA', 'TRUJILLO'],
      ['VALLE DEL CAUCA', 'TULUÁ'],
      ['VALLE DEL CAUCA', 'ULLOA'],
      ['VALLE DEL CAUCA', 'VERSALLES'],
      ['VALLE DEL CAUCA', 'VIJES'],
      ['VALLE DEL CAUCA', 'YOTOCO'],
      ['VALLE DEL CAUCA', 'YUMBO'],
      ['VALLE DEL CAUCA', 'ZARZAL'],
      ['ARAUCA', 'ARAUCA'],
      ['ARAUCA', 'ARAUQUITA'],
      ['ARAUCA', 'CRAVO NORTE'],
      ['ARAUCA', 'FORTUL'],
      ['ARAUCA', 'PUERTO RONDÓN'],
      ['ARAUCA', 'SARAVENA'],
      ['ARAUCA', 'TAME'],
      ['CASANARE', 'YOPAL'],
      ['CASANARE', 'AGUAZUL'],
      ['CASANARE', 'CHÁMEZA'],
      ['CASANARE', 'HATO COROZAL'],
      ['CASANARE', 'LA SALINA'],
      ['CASANARE', 'MANÍ'],
      ['CASANARE', 'MONTERREY'],
      ['CASANARE', 'NUNCHÍA'],
      ['CASANARE', 'OROCUÉ'],
      ['CASANARE', 'PAZ DE ARIPORO'],
      ['CASANARE', 'PORE'],
      ['CASANARE', 'RECETOR'],
      ['CASANARE', 'SABANALARGA'],
      ['CASANARE', 'SÁCAMA'],
      ['CASANARE', 'SAN LUIS DE PALENQUE'],
      ['CASANARE', 'TÁMARA'],
      ['CASANARE', 'TAURAMENA'],
      ['CASANARE', 'TRINIDAD'],
      ['CASANARE', 'VILLANUEVA'],
      ['PUTUMAYO', 'MOCOA'],
      ['PUTUMAYO', 'COLÓN'],
      ['PUTUMAYO', 'ORITO'],
      ['PUTUMAYO', 'PUERTO ASÍS'],
      ['PUTUMAYO', 'PUERTO CAICEDO'],
      ['PUTUMAYO', 'PUERTO GUZMÁN'],
      ['PUTUMAYO', 'PUERTO LEGUÍZAMO'],
      ['PUTUMAYO', 'SIBUNDOY'],
      ['PUTUMAYO', 'SAN FRANCISCO'],
      ['PUTUMAYO', 'SAN MIGUEL'],
      ['PUTUMAYO', 'SANTIAGO'],
      ['PUTUMAYO', 'VALLE DEL GUAMUEZ'],
      ['PUTUMAYO', 'VILLAGARZÓN'],
      ['ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA', 'SAN ANDRÉS'],
      ['ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA', 'PROVIDENCIA'],
      ['AMAZONAS', 'LETICIA'],
      ['AMAZONAS', 'EL ENCANTO'],
      ['AMAZONAS', 'LA CHORRERA'],
      ['AMAZONAS', 'LA PEDRERA'],
      ['AMAZONAS', 'LA VICTORIA'],
      ['AMAZONAS', 'MIRITÍ - PARANÁ'],
      ['AMAZONAS', 'PUERTO ALEGRÍA'],
      ['AMAZONAS', 'PUERTO ARICA'],
      ['AMAZONAS', 'PUERTO NARIÑO'],
      ['AMAZONAS', 'PUERTO SANTANDER'],
      ['AMAZONAS', 'TARAPACÁ'],
      ['GUAINÍA', 'INÍRIDA'],
      ['GUAINÍA', 'BARRANCOMINAS'],
      ['GUAINÍA', 'SAN FELIPE'],
      ['GUAINÍA', 'PUERTO COLOMBIA'],
      ['GUAINÍA', 'LA GUADALUPE'],
      ['GUAINÍA', 'CACAHUAL'],
      ['GUAINÍA', 'PANA PANA'],
      ['GUAINÍA', 'MORICHAL'],
      ['GUAVIARE', 'SAN JOSÉ DEL GUAVIARE'],
      ['GUAVIARE', 'CALAMAR'],
      ['GUAVIARE', 'EL RETORNO'],
      ['GUAVIARE', 'MIRAFLORES'],
      ['VAUPÉS', 'MITÚ'],
      ['VAUPÉS', 'CARURÚ'],
      ['VAUPÉS', 'PACOA'],
      ['VAUPÉS', 'TARAIRA'],
      ['VAUPÉS', 'PAPUNAHUA'],
      ['VAUPÉS', 'YAVARATÉ'],
      ['VICHADA', 'PUERTO CARREÑO'],
      ['VICHADA', 'LA PRIMAVERA'],
      ['VICHADA', 'SANTA ROSALÍA'],
      ['VICHADA', 'CUMARIBO']
  ]
  end
end
